apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-hyperstack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}-attacher-cluster-role
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: attacher-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-hyperstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}-health-monitor-controller-cluster-role
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-hyperstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}-provisioner-cluster-role
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-hyperstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}-resizer-cluster-role
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: resizer-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-resizer-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-hyperstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}-snapshotter-cluster-role
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: snapshotter-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshotter-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-hyperstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
